import click
from parser import parse_log_file, display_results, extract_filenames, extract_file_function_map
from github import fetch_file_from_github, get_repo_file_tree, find_full_path, find_file_by_function,get_default_branch
from crashdump import diagnose_from_report, extract_file_and_line
from ai import analyze_logs
import os 
import json
import httpx
from rich.console import Console

console=Console()

def _load_api_key_from_config():
    if os.path.exists('.roota.json'):
        with open('.roota.json', 'r') as f:
            config = json.load(f)
            return config.get('api_key')
    return None


def _load_server_from_config():
    if os.path.exists('.roota.json'):
        with open('.roota.json', 'r') as f:
            config = json.load(f)
            return config.get('server', 'https://tryroota.dev')
    return 'https://tryroota.dev'

@click.command(help="debugai — AI-powered production log analyzer.\n\nAnalyzes log files, fetches relevant source code from GitHub, and produces AI-powered diagnoses with exact root causes and fixes.")
@click.version_option(version="0.1.0", prog_name="debugai")
@click.option('--log', required=True, help='Path to the log file to analyze (supports plain text, JSON logs, structured formats)')
@click.option('--repo', required=False, help='GitHub repository in format owner/repo. When provided, fetches relevant source files for deeper analysis.')
@click.option('--crash-report', required=False, help='Path to a C++ crash_report.log generated by debugai_handler.h. Enables exact crash address resolution.')
@click.option('--sync', is_flag=True, help='Send this analysis to your Roota dashboard (requires an API key).')
@click.option('--api-key', required=False, help='Your Roota API key. If not provided, reads from .roota.json if present.')
def main(log, repo, crash_report,sync, api_key):
    console.print("\n[bold cyan]debugai[/bold cyan] [dim]v0.1.0 — AI-powered production debugger[/dim]\n")
    if os.path.exists(log):
        entries, errors, warnings = parse_log_file(log)
        display_results(entries, errors, warnings)
        code_context = None

        if repo:
            filenames = extract_filenames(errors)
            repo = repo.strip().strip('/')
            parts = repo.split('/')
            if len(parts) != 2:
                console.print(f"[bold red]Invalid --repo format: '{repo}'. Expected 'owner/repo_name'.[/bold red]")
                raise click.Abort()
            owner, repo_name = parts[0], parts[1]
            branch = get_default_branch(owner, repo_name)
            code_context = {}

            file_tree = get_repo_file_tree(owner, repo_name, branch)
            file_function_map = extract_file_function_map(errors)

            for filename in filenames:
                if filename in file_function_map:
                    function_name = file_function_map[filename]
                    full_path = find_file_by_function(filename, function_name, file_tree, owner, repo_name, branch)
                else:
                    full_path = find_full_path(filename, file_tree)
                if full_path:
                    content = fetch_file_from_github(owner, repo_name, full_path, branch)
                    if content:
                        code_context[filename] = content

        cpp_crash_info = None

        if crash_report:
            location = diagnose_from_report(crash_report)
            cpp_filename, cpp_line = extract_file_and_line(location)
            cpp_crash_info = {"filename": cpp_filename, "line": cpp_line}

            if repo:
                if code_context is None:
                    code_context = {}

                full_path = find_full_path(cpp_filename, file_tree)
                if full_path:
                    content = fetch_file_from_github(owner, repo_name, full_path, branch)
                    if content:
                        code_context[cpp_filename] = content

        diagnosis = analyze_logs(entries, errors, warnings, code_context, cpp_crash_info)

        if sync:
            key = api_key or _load_api_key_from_config()
            if not key:
                console.print("[bold red]--sync requires an API key. Pass --api-key or set one in .roota.json.[/bold red]")
                raise click.Abort()

            with open(log, 'r', encoding='utf-8') as f:
                log_text = f.read()

            console.print("\n[dim]Syncing to Roota dashboard...[/dim]")
            try:
                server = _load_server_from_config()
                response = httpx.post(
                    f"{server}/ingest",
                    json={
                        "log_text": log_text,
                        "repo": repo,
                        "source": "cli"
                    },
                    headers={"X-API-Key": key},
                    timeout=30
                )
                data = response.json()
                if data.get("status") == "success":
                    console.print(f"[bold green]Synced. Incident #{data['incident_id']} saved to your dashboard.[/bold green]")
                else:
                    console.print(f"[bold red]Sync failed: {data.get('message', response.text)}[/bold red]")
            except Exception as e:
                console.print(f"[bold red]Could not sync: {e}[/bold red]")
    else:
        console.print(f"[bold red]File '{log}' doesnt exist[/bold red]")
        raise click.Abort()
if __name__ == '__main__':
    main()
    